jwt_token: 3BTBXHS570HT7711P1YLUO106K3A1BU6N7CDQCH5B2TACIVNBR # 请替换为自己的 JWT Token
upstream: http://10.21.7.123:6666/
bawiki_data: https://bawiki.lgc2333.top/
fastapi:
  host: 0.0.0.0
  port: 8080
  debug: False
  reload: False
  log_level: info
  title: Arona Helper Backend
  description: Arona Helper Backend API
database:
  # https://docs.sqlalchemy.org/en/13/core/engines.html
  dialect: mysql # mysql / postgresql / oracle / mssql / sqlite / etc.
  driver: pymysql # need driver supported dialect
  host: 127.0.0.1 # HostName / FilePath
  port: 3306 # 如不需要可以删掉
  username: example
  password: example
  db: example
  args: "charset=utf8mb4"
  debug: False