secret:
  jwt_secret: 3BTBXHS570HT7711P1YLUO106K3A1BU6N7CDQCH5B2TACIVNBR # 请替换为自己的 JWT Token
  jwt_algorithm: HS256
  bot_req_token: ZBYTEOUFEPRHSIQERZHOBMIEVQBWSPVJLVZLYTFLFEXNSKWLIX # 请替换为自己的 Bot 请求 Token 
upstream: http://10.21.7.123:6666/
bawiki_data: https://bawiki.lgc2333.top/
fastapi:
  host: 0.0.0.0
  port: 8080
  log_level: info
  title: Arona Helper Backend
  description: Arona Helper Backend API
database:
  redis:
    url: "redis://[[username]:[password]]@localhost:6379/0"
  mysql:
    host: localhost
    port: 3306
    user: root
    password: root
    database: arona
    chatset: utf8mb4